import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
  },
  containerOne: {
    flexDirection: "row",
    paddingTop: 20,
    paddingLeft: 15,
    alignItems: "center",
  },
  userName: {
    color: "#032955",
    fontSize: 20,
    fontWeight: "bold",
  },
  containerTwo: {
    flexDirection: "row",
    paddingLeft: 45,
    marginVertical: 15,
  },
  image: {
    borderRadius: 70,
    width: 100,
    height: 100,
  },
  editButton: {
    elevation: 8,
    position: "absolute",
    backgroundColor: "#1648AD",
    borderRadius: 50,
    paddingVertical: 10,
    paddingHorizontal: 20,
    right: 20,
    top: 30,
  },
  buttonText: {
    fontSize: 18,
    color: "#fff",
    fontWeight: "bold",
    alignSelf: "center",
  },
  headerSendNotification: {
    width: "100%",
    height: 40,
    alignItems: "flex-end",
  },
  imageProfile: {
    alignItems: "center",
    marginBottom: 30,
  },
  option: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingVertical: 20,
    marginHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#1648AD",
  },
  appButtonContainer: {
    elevation: 8,
    backgroundColor: "#1648AD",
    borderRadius: 50,
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginVertical: 20,
  },
  deleteCarButton: {
    elevation: 8,
    backgroundColor: "red",
    borderRadius: 50,
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  appButtonText: {
    fontSize: 18,
    color: "#fff",
    fontWeight: "bold",
    alignSelf: "center",
    paddingHorizontal: 20,
  },
  addButton: {
    position: "absolute",
    marginTop: 530,
    marginLeft: 320,
    bottom: 10,
    right: 20,
    // zIndex: 10000,
  },
  titleVehicle: {
    marginLeft: 20,
    marginVertical: 10,
    fontSize: 18,
    color: "#032955",
    fontWeight: "bold",
  },
  default: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  textPopUp: {
    fontSize: 18,
    color: "#1648AD",
  },
  yourVehicle: {
    fontSize: 18,
    color: "#1648AD",
    fontWeight: "bold",
    marginLeft: 20,
    marginVertical: 10,
  },
  uploadImage: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    color: "#1648AD",
    marginVertical: 10,
  },
  vehiclesHeader: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginVertical: 5,
  },
  addCarButton: {
    elevation: 8,
    backgroundColor: "#1648AD",
    borderRadius: 50,
    color: "#fff",
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
});

export default styles;
